# Generated by Django 4.1.3 on 2022-11-20 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_posts_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ('-publish',)},
        ),
        migrations.AlterField(
            model_name='posts',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
