# Generated by Django 4.1.3 on 2022-11-26 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_categories_posts_category'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categories',
            table='Category',
        ),
    ]
