# Generated by Django 4.1.3 on 2022-11-26 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_categories_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='slug',
        ),
    ]
